default: &default
  host: <%= ENV.fetch("REDIS_HOST") { 'redis' } %>
  port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
  username: <%= ENV.fetch("REDIS_USERNAME") { 'default' } %>
  password: <%= ENV.fetch("REDIS_PASSWORD") { } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
